config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Refactorizamos con el comando resources todas nuestras vistas
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products', to:'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end
  resources :favorites, only: [:index, :create, :destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path: '/'

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    
    has_many :products, dependent: :restrict_with_exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_action :set_category, only: %i[ show edit update destroy ]

  before_action :approved!
  # GET /categories or /categories.json
  def index
    @categories = Category.all.order(name: :asc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    category
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category.destroy

    redirect_to categories_url, notice: t('.destroyed')
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="flex justify-between " id="<%= dom_id category %>">  
      <div class=" w-1/3  rounded-2xl  cursor-text text-center  my-4  py-2  text-gray-600 bg-white ">  
      <%= category.name %> 
      </div>

   

      <div class=" w-1/3  rounded-2xl  cursor-text text-center my-4  py-2 transition ease-in-out delay-150  hover:-translate-y-0 hover:scale-75 hover:bg-green-300 duration-300  ">   
        <%= link_to t('.edit'), edit_category_path(category) %>       
     </div>
    

      <div class=" w-1/3  rounded-2xl  cursor-text text-center my-4  py-2 transition ease-in-out delay-150  hover:-translate-y-0 hover:scale-75 hover:bg-red-300 duration-300 ">   
        <%= link_to t('.delete'), category_path(category), data: {
        turbo_method: :delete,
        turbo_confirm: t('common.confirm')
        } %>
      </div>

  
 
 
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div class="  rounded-2xl font-bold cursor-text text-center my-4  py-4 text-orange-400 bg-blue-200 ">
    <%= form.label :name %>
    <%= form.text_field :name, class: " rounded-2xl text-center text-gray-400" %>
  </div>

  <div class="rounded-2xl font-bold cursor-text text-center my-2 py-2 text-orange-600  ">
    <div class="transition ease-in-out delay-150  hover:-translate-y-2 hover:scale-90 rounded-2xl hover:bg-green-400 duration-300 ... ">    
    <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class= " text-2xl rounded-2xl font-bold cursor-text text-center my-2  py-2 text-orange-600 bg-blue-200 "><%= t('.title') %></h1>


       <%= render "form", category: @category %>

<div class=" rounded-2xl font-bold cursor-text text-center  my-2  py-2 text-orange-600 bg-blue-200 ">
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1 class=" text-2xl rounded-2xl font-bold cursor-text text-center my-2  py-2 text-orange-600 bg-blue-200 "><%= t('.title') %></h1>

     <%= render partial: 'category', collection: @categories %>
<div class=" rounded-2xl font-bold cursor-text text-center  my-2  py-2 text-orange-600 bg-blue-200 ">
      <%= link_to t('.new'), new_category_path %>
</div>      

app/views/categories/new.html.erb
<h1 class= " text-2xl rounded-2xl font-bold cursor-text text-center my-2  py-2 text-orange-600 bg-blue-200 " ><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div class=" rounded-2xl font-bold cursor-text text-center  my-2  py-2 text-orange-600 bg-blue-200 ">
  <%= link_to t('common.back'), categories_path %>
</div>