config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Refactorizamos con el comando resources todas nuestras vistas
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products', to:'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end
  resources :favorites, only: [:index, :create, :destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path: '/'

end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable

  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }
  
  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }

  has_one_attached :image

  validates :title, length: {minimum: 5, maximum: 25},presence: true
  validates :description, length: {minimum: 25, maximum: 130},presence: true
  validates :price, presence: true
  
  
  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  def owner?
    user_id == Current.user&.id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :protect_pages, only: [:index, :show]
    def index
      @categories = Category.order(name: :asc).load_async     
      @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 8)
    end

    def show
       product 
    end

    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(product_params)
    
        if @product.save
          redirect_to products_path, notice: t('.created')
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit      
        approved! product # product.user_id == Currebt.user.id
    end
    
    def update       
        approved! product
        if product.update(product_params)
          redirect_to products_path, notice:  t('.updated')
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        approved! product
        product.destroy
    
        redirect_to products_path, notice: t('.destroyed'), status: :see_other
    end

      private
    
      def product_params
        params.require(:product).permit(:title, :description, :price, :image, :category_id)
      end

      def product_params_index
        params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites, :user_id)
      end

      def product
        @product ||= Product.find(params[:id])
      end
    
  end

app/views/products/_category.html.erb
<%
=begin%>
 <%= link_to products_path(category_id: category.id), class: 'category bg-orange-200  text-gray-600   px-4 py-2 rounded-2xl  hover:bg-blue-200  ' do %>
  <%= category.name %>
<% end %> 
<%
=end%>

app/views/products/_favorite.html.erb
<div id="favorite">
    <% if product.favorite %>
     <%= link_to '❌💔', favorites_path( product.id), data: {
      turbo_method: :delete,
      turbo_confirm: t('common.confirm')
  
     } %>
    <% else %>
     <%= link_to '✅💘', favorites_path(product_id: product.id), data: {
       turbo_method: :post
     } %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>


  <div >
    <%= form.label :title,class:"text-orange-600" %>
    <%= form.text_field :title, class:" rounded-2xl cursor-text text-center  my-2  py-2 text-orange-400 bg-white " %>
  </div>

  <div class="" >
    <%= form.label :description,class:"text-orange-600" %>
    <%= form.text_area :description, class:" rounded-2xl py-2 text-orange-400 bg-white " %>
  </div>

  <div >
    <%= form.label :price,class:"text-orange-600" %>
    <%= form.number_field :price,step: 0.01, class:" rounded-2xl  my-2  py-2 text-orange-400 bg-white " %>
  </div>

  <div  >
    <%= form.label :category_id, :Seccion,class:"text-orange-600" %>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name  %>
  </div>

  <div >
    <%= form.label :image,class:"text-orange-600" %>
    <%= form.file_field :image %>
  </div>
  <div class="rounded-2xl font-bold  text-orange-600  text-center my-2  py-2 transition ease-in-out delay-150  hover:-translate-y- hover:scale-90 rounded-2xl hover:bg-green-400 duration-300 ... ">
  <%= form.submit t('.Create') %>
  </div>

<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product bg-white mb-2 rounded-2xl rounded sm:bg-orange-200 sm:w-[calc(33.33333%_-_.5rem)] lg:w-[calc(25%_-_.5rem)]', 'data-turbo-frame': '_top' do %>
    <div class="m-2">
         <h3><strong>Modelo:</strong> <%= product.title  %></h3>&rarr;
         <span class="font-bold text-orange-600"><%= product.price %>€</span>
    </div>
    <%= image_tag product.image.attached? ?  product.image : 'placeholder.jpg' , class:"w-full rounded-2xl h-60 object-cover" %>
    <p class="text-gray-600 mt-2 text-sm"><%=product.description %> </p>
<% end %>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
  <div class="  text-2xl rounded-2xl font-bold cursor-text text-center my-2  py-2 text-orange-600 bg-blue-200 ">   
      <h2><%= t('.title') %></h2> 
  </div>
  <div class="flex justify-between overflow-x-scroll gap-2 px-2 py-2 my-4">
      <%= render(CategoryComponent.new) %>       
      <%= render(CategoryComponent.with_collection(@categories)) %>
  </div>
  <%= form_with url: products_path, method: :get do |form| %>
       <%=form.text_field :query_text, placeholder: t('.query_text'),
           onChange: 'this.form.requestSubmit()', value: params[:query_text], class: "w-full my-2 rounded-2xl border-orange-200"%>
          <div class= "flex ">
            <%=form.number_field :min_price, placeholder: t('.min_price'),
             onChange: 'this.form.requestSubmit()', value: params[:min_price], class: "w-1/3 rounded-2xl  border-orange-200 "%>
            <%=form.number_field :max_price, placeholder: t('.max_price'),
             onChange: 'this.form.requestSubmit()', value: params[:max_price], class: "w-1/3 rounded-2xl mx-2 border-orange-200 "%>
            <%=form.select :order_by, options_for_select(Product::ORDER_BY.keys.map{|order|[t(".#{order}"), order]}, params[:order_by]),{},
             {onChange: 'this.form.requestSubmit()', class: "w-1/3 rounded-2xl border-orange-200 text-gray-600"} %>
          </div>
    <% end %>

    <%=turbo_frame_tag :products, class:" flex flex-col m-2 "  do %>
      <%=turbo_frame_tag "products-#{@pagy.page}", class: "products flex flex-col w-full  sm:flex-row sm:flex-wrap sm:gap-x-2" do %>
        <%= render partial: 'product', collection: @products %>
        <%= turbo_frame_tag "products-#{@pagy.next}", class: "products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2", src: pagy_url_for(@pagy, @pagy.next),
            loading: :lazy  if @pagy.next %>
       <%end %> 
    <%end %>
<% end %>

app/views/products/new.html.erb
<%= turbo_frame_tag "modal" do %>
 <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-gray bg-opacity-40"></div>
      <div  data-modal-target="sidebar_add" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-blue-200 rounded-2xl overflow-y-scroll  flex flex-col ease-in-out duration-300 p-5 translate-x-full">
        <p class="cursor-pointer mb-4" data-action="click->modal#close">❌</p>
         <h2 class="font-bold  text-2xl mb-4 text-orange-600"><%= t('.title') %></h2>
         <%= render 'form' %>
      </div>
 </div>
<% end %>

app/views/products/show.html.erb
<h1 class='title rounded-2xl font-bold  text-center my-4  py-2 text-orange-400 bg-blue-200 '><%= @product.title %></h1>

<%= image_tag @product.image,class:" object-cover  md:container md:mx-auto " if @product.image.attached? %>

<p class='description  rounded-2xl font-bold text-center my-4  py-2  bg-blue-200 '><%= @product.description %></p>

<div class='price  rounded-2xl font-bold text-center text-orange-400 my-4  py-2  bg-blue-200 ' >
---><%= @product.price %>€<---
<%= render partial: 'favorite', locals: { product: @product } %>
</div>

<%= link_to t('.edit'), edit_product_path(@product) if @product.owner? %>
<%= link_to t('.delete'), product_path(@product), data: {
  turbo_method: :delete,
  turbo_confirm: t('common.confirm')
  } if @product.owner? %>
<p class=' rounded-2xl  text-center my-4  py-2  bg-blue-200 '>
<%= link_to t('.view_more_products', username: @product.user.username), user_path(@product.user.username) %>

</p>